<?php

use My\CustomDescriptionToProduct\Block\CommentsList;

/** @var $block CommentsList */
?>

<h2><b>Custom comments list:</b></h2>
<div>
    <?php /* @noEscape */
    if ($block->checkIsEmpty() != 'empty') {
        foreach ($block->getCommentList() as $comment) : ?>
        <div class="extra-comment" style="border-style: double;">
            <p><b>Name:</b>
                <?= /* @noEscape */ $block->getCustomerName($comment['customer_email']) ?>
            </p>
            <b>Comment:</b>
            <span class="extra-comment-child">
                <?= /* @noEscape */ $comment['custom_customer_description_to_product'] ?>
            </span>
            <br/>
        </div>
        <br/>
    <?php endforeach;
    } else {
        echo 'There is no comments yet...';
    } ?>
</div>
